##### creating a namespace to make all the services - pods arrenged 
##### always stick to a namespace for your project to stay away from other stuff that kube is making or other teams

apiVersion: v1
kind: Namespace
metadata:
  name:  my-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-namespace
  name: api-gateway-service
  labels:
    bb: jee-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: jee-microservices
  template:
    metadata:
      labels:
        bb: jee-microservices
    spec:
      containers:
      - name: api-gateway-service
        image: jee-microservices-startup_api-gateway
        ports:
        - containerPort: 8000
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  namespace: my-namespace
  name: api-gateway
spec:
  selector:
    bb: jee-microservices
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer